### ISSUE TITLE
reference model weights

### ISSUE THREAD

**Issue by zhenwu0831** [QiyaoWei/Reproduce-DPO#1]
Hi, 

We are also reproducing dpo, and are wondering that whether you have saved the weights of gpt2-large model that is finetuned on the preference dataset for 3 epochs as the paper suggested? Is this the model: https://huggingface.co/QiyaoWei/Vanilla-SFT-GPT2Large/tree/main

Thank you so much!!

**Comment by QiyaoWei** [comment]
In my personal experience, SFT is not required for the IMDB experiments. I think you can even get away with not doing SFT on HH, but bottomline is you should be able to reproduce IMDB by directly running DPO

**Comment by zhenwu0831** [comment]
Hmm what I'm confused with is the reference model in reproducing imdb, is the vanilla-sft-gpt2 large model I referenced above your reference model?

**Comment by QiyaoWei** [comment]
I just used openai-community/gpt2-large

**Comment by QiyaoWei** [comment]
Closing this issue now due to lack of activity
